module.exports.constants = {
  UNAUTHENTICATED_USER_HEADER: 'notSignedIn',

  USER_UNAUTHENTICATED: 'UNAUTHENTICATED',
  USER_AUTHENTICATED: 'AUTHENTICATED',
  USER_ADMIN: 'ADMIN',
  ACCESS_TOKEN_NOTFOUND: 'ACCESS_TOKEN_NOTFOUND',
  FORBIDDEN: 'FORBIDDEN'
};
